### 회원 가입 (POST)
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "김감자"
}

### 전체 회원 조회 (GET)
GET http://localhost:8080/members
### 전체 회원 및 팀 조회 (GET)
GET http://localhost:8080/members/teams

### 전체 회원 및 구독 조회 (GET)
GET http://localhost:8080/members/subscriptions
### persist 테스트(GET)
GET http://localhost:8080/test

### proxy 테스트(GET)
GET http://localhost:8080/proxyTest